// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAliceHome() {
  return window['go']['main']['App']['GetAliceHome']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function IsGatewayHealthy() {
  return window['go']['main']['App']['IsGatewayHealthy']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function PathExists(arg1) {
  return window['go']['main']['App']['PathExists'](arg1);
}

export function ProxyApi(arg1) {
  return window['go']['main']['App']['ProxyApi'](arg1);
}

export function ReadFileDataUrl(arg1) {
  return window['go']['main']['App']['ReadFileDataUrl'](arg1);
}

export function ReadFileText(arg1) {
  return window['go']['main']['App']['ReadFileText'](arg1);
}

export function RenamePath(arg1, arg2) {
  return window['go']['main']['App']['RenamePath'](arg1, arg2);
}

export function RestartGateway() {
  return window['go']['main']['App']['RestartGateway']();
}

export function RevealLogs() {
  return window['go']['main']['App']['RevealLogs']();
}

export function RevealPath(arg1) {
  return window['go']['main']['App']['RevealPath'](arg1);
}

export function TrashPath(arg1) {
  return window['go']['main']['App']['TrashPath'](arg1);
}

export function WriteErrorLog(arg1) {
  return window['go']['main']['App']['WriteErrorLog'](arg1);
}

export function WriteFrontendLog(arg1) {
  return window['go']['main']['App']['WriteFrontendLog'](arg1);
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['main']['App']['WriteTextFile'](arg1, arg2);
}
