// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function OpenExternal(arg1:string):Promise<void>;

export function PathExists(arg1:string):Promise<boolean>;

export function ReadDir(arg1:string):Promise<Array<Record<string, any>>>;

export function ReadFileDataUrl(arg1:string):Promise<string>;

export function ReadFileText(arg1:string):Promise<string>;

export function RenamePath(arg1:string,arg2:string):Promise<string>;

export function RevealPath(arg1:string):Promise<void>;

export function SaveClipboardImage():Promise<string>;

export function SaveImageBuffer(arg1:Array<number>,arg2:string):Promise<string>;

export function SelectPaths(arg1:main.SelectPathsRequest):Promise<Array<string>>;

export function TrashPath(arg1:string):Promise<void>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;
