// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogsDir():Promise<string>;

export function GetRecentLogs(arg1:number):Promise<Array<string>>;

export function RevealLogs():Promise<void>;
