// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisposeTerminal(arg1) {
  return window['go']['main']['PTYService']['DisposeTerminal'](arg1);
}

export function ReadTerminal(arg1) {
  return window['go']['main']['PTYService']['ReadTerminal'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['PTYService']['ResizeTerminal'](arg1, arg2, arg3);
}

export function StartTerminal(arg1, arg2, arg3) {
  return window['go']['main']['PTYService']['StartTerminal'](arg1, arg2, arg3);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['PTYService']['WriteTerminal'](arg1, arg2);
}
