// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DisposeTerminal(arg1:string):Promise<void>;

export function ReadTerminal(arg1:string):Promise<string>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function StartTerminal(arg1:string,arg2:number,arg3:number):Promise<main.TerminalSession>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
