// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAliceHome() {
  return window['go']['main']['PythonManager']['GetAliceHome']();
}

export function GetConnectionInfo() {
  return window['go']['main']['PythonManager']['GetConnectionInfo']();
}

export function GetSessionToken() {
  return window['go']['main']['PythonManager']['GetSessionToken']();
}

export function IsHealthy() {
  return window['go']['main']['PythonManager']['IsHealthy']();
}

export function ResolveProjectRoot() {
  return window['go']['main']['PythonManager']['ResolveProjectRoot']();
}

export function StartGateway() {
  return window['go']['main']['PythonManager']['StartGateway']();
}

export function StopGateway() {
  return window['go']['main']['PythonManager']['StopGateway']();
}

export function WaitForHealthy(arg1) {
  return window['go']['main']['PythonManager']['WaitForHealthy'](arg1);
}

export function WriteFrontendLog(arg1) {
  return window['go']['main']['PythonManager']['WriteFrontendLog'](arg1);
}
