// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAliceHome():Promise<string>;

export function GetBackendPIDs():Promise<Array<number>>;

export function GetConnectionInfo():Promise<main.ConnectionInfo>;

export function GetSessionToken():Promise<string>;

export function IsHealthy():Promise<boolean>;

export function ResolveProjectRoot():Promise<string>;

export function StartGateway():Promise<void>;

export function StopGateway():Promise<void>;

export function WaitForHealthy(arg1:number):Promise<boolean>;

export function WriteFrontendLog(arg1:string):Promise<void>;
