// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAliceHome():Promise<string>;

export function GetConnectionInfo():Promise<main.ConnectionInfo>;

export function GetRecentLogs(arg1:number):Promise<Array<string>>;

export function IsGatewayHealthy():Promise<boolean>;

export function OpenExternal(arg1:string):Promise<void>;

export function PathExists(arg1:string):Promise<boolean>;

export function ProxyApi(arg1:main.ProxyApiRequest):Promise<main.ProxyApiResponse>;

export function ReadFileDataUrl(arg1:string):Promise<string>;

export function ReadFileText(arg1:string):Promise<string>;

export function RenamePath(arg1:string,arg2:string):Promise<string>;

export function RestartGateway():Promise<void>;

export function RevealLogs():Promise<void>;

export function RevealPath(arg1:string):Promise<void>;

export function TrashPath(arg1:string):Promise<void>;

export function WriteErrorLog(arg1:string):Promise<void>;

export function WriteFrontendLog(arg1:string):Promise<void>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;
