// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Get():Promise<main.ConnectionConfig>;

export function IsRemote():Promise<boolean>;

export function ProbeRemote(arg1:string,arg2:string):Promise<main.ProbeResult>;

export function Set(arg1:main.ConnectionConfig):Promise<main.ConnectionConfig>;