// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get() {
  return window['go']['main']['ConnectionService']['Get']();
}

export function IsRemote() {
  return window['go']['main']['ConnectionService']['IsRemote']();
}

export function ProbeRemote(arg1, arg2) {
  return window['go']['main']['ConnectionService']['ProbeRemote'](arg1, arg2);
}

export function Set(arg1) {
  return window['go']['main']['ConnectionService']['Set'](arg1);
}