// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenExternal(arg1) {
  return window['go']['main']['FSService']['OpenExternal'](arg1);
}

export function PathExists(arg1) {
  return window['go']['main']['FSService']['PathExists'](arg1);
}

export function ReadDir(arg1) {
  return window['go']['main']['FSService']['ReadDir'](arg1);
}

export function ReadFileDataUrl(arg1) {
  return window['go']['main']['FSService']['ReadFileDataUrl'](arg1);
}

export function ReadFileText(arg1) {
  return window['go']['main']['FSService']['ReadFileText'](arg1);
}

export function RenamePath(arg1, arg2) {
  return window['go']['main']['FSService']['RenamePath'](arg1, arg2);
}

export function RevealPath(arg1) {
  return window['go']['main']['FSService']['RevealPath'](arg1);
}

export function SaveClipboardImage() {
  return window['go']['main']['FSService']['SaveClipboardImage']();
}

export function SaveImageBuffer(arg1, arg2) {
  return window['go']['main']['FSService']['SaveImageBuffer'](arg1, arg2);
}

export function SelectPaths(arg1) {
  return window['go']['main']['FSService']['SelectPaths'](arg1);
}

export function TrashPath(arg1) {
  return window['go']['main']['FSService']['TrashPath'](arg1);
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['main']['FSService']['WriteTextFile'](arg1, arg2);
}
