// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWorktree(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Commit(arg1:string,arg2:string):Promise<void>;

export function GetCurrentBranch(arg1:string):Promise<string>;

export function GetFileDiff(arg1:string,arg2:string):Promise<string>;

export function GetGitRoot(arg1:string):Promise<string>;

export function GetRecentCommits(arg1:string,arg2:number):Promise<Array<string>>;

export function GetRemoteURL(arg1:string):Promise<string>;

export function GetStatus(arg1:string):Promise<string>;

export function ListBranches(arg1:string):Promise<Array<string>>;

export function ListWorktrees(arg1:string):Promise<Array<string>>;

export function Push(arg1:string):Promise<void>;

export function RemoveWorktree(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function RevParse(arg1:string,arg2:string):Promise<string>;

export function RevertFile(arg1:string,arg2:string):Promise<void>;

export function StageFile(arg1:string,arg2:string):Promise<void>;

export function SwitchBranch(arg1:string,arg2:string):Promise<void>;

export function UnstageFile(arg1:string,arg2:string):Promise<void>;
