// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWorktree(arg1, arg2, arg3) {
  return window['go']['main']['GitService']['AddWorktree'](arg1, arg2, arg3);
}

export function Commit(arg1, arg2) {
  return window['go']['main']['GitService']['Commit'](arg1, arg2);
}

export function GetCurrentBranch(arg1) {
  return window['go']['main']['GitService']['GetCurrentBranch'](arg1);
}

export function GetFileDiff(arg1, arg2) {
  return window['go']['main']['GitService']['GetFileDiff'](arg1, arg2);
}

export function GetGitRoot(arg1) {
  return window['go']['main']['GitService']['GetGitRoot'](arg1);
}

export function GetRecentCommits(arg1, arg2) {
  return window['go']['main']['GitService']['GetRecentCommits'](arg1, arg2);
}

export function GetRemoteURL(arg1) {
  return window['go']['main']['GitService']['GetRemoteURL'](arg1);
}

export function GetStatus(arg1) {
  return window['go']['main']['GitService']['GetStatus'](arg1);
}

export function ListBranches(arg1) {
  return window['go']['main']['GitService']['ListBranches'](arg1);
}

export function ListWorktrees(arg1) {
  return window['go']['main']['GitService']['ListWorktrees'](arg1);
}

export function Push(arg1) {
  return window['go']['main']['GitService']['Push'](arg1);
}

export function RemoveWorktree(arg1, arg2, arg3) {
  return window['go']['main']['GitService']['RemoveWorktree'](arg1, arg2, arg3);
}

export function RevParse(arg1, arg2) {
  return window['go']['main']['GitService']['RevParse'](arg1, arg2);
}

export function RevertFile(arg1, arg2) {
  return window['go']['main']['GitService']['RevertFile'](arg1, arg2);
}

export function StageFile(arg1, arg2) {
  return window['go']['main']['GitService']['StageFile'](arg1, arg2);
}

export function SwitchBranch(arg1, arg2) {
  return window['go']['main']['GitService']['SwitchBranch'](arg1, arg2);
}

export function UnstageFile(arg1, arg2) {
  return window['go']['main']['GitService']['UnstageFile'](arg1, arg2);
}
