// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogsDir() {
  return window['go']['main']['LogService']['GetLogsDir']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['LogService']['GetRecentLogs'](arg1);
}

export function RevealLogs() {
  return window['go']['main']['LogService']['RevealLogs']();
}
