// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Apply(arg1:main.UpdateApplyOptions):Promise<main.UpdateApplyResult>;

export function Check():Promise<main.UpdateStatus>;

export function GetBranch():Promise<{[key: string]: string}>;

export function GetVersion():Promise<main.DesktopVersionInfo>;

export function SetBranch(arg1:string):Promise<{[key: string]: string}>;
