// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function Apply(arg1:main.UpdateApplyOptions):Promise<main.UpdateApplyResult>;

export function Check():Promise<main.UpdateStatus>;

export function GetBranch():Promise<Record<string, string>>;

export function GetVersion():Promise<main.DesktopVersionInfo>;

export function SetBranch(arg1:string):Promise<Record<string, string>>;

export function SetContext(arg1:context.Context,arg2:string):Promise<void>;
