// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Apply(arg1) {
  return window['go']['main']['UpdateService']['Apply'](arg1);
}

export function Check() {
  return window['go']['main']['UpdateService']['Check']();
}

export function GetBranch() {
  return window['go']['main']['UpdateService']['GetBranch']();
}

export function GetVersion() {
  return window['go']['main']['UpdateService']['GetVersion']();
}

export function SetBranch(arg1) {
  return window['go']['main']['UpdateService']['SetBranch'](arg1);
}

export function SetContext(arg1, arg2) {
  return window['go']['main']['UpdateService']['SetContext'](arg1, arg2);
}
